-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema creditos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `creditos` ;

-- -----------------------------------------------------
-- Schema creditos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creditos` DEFAULT CHARACTER SET utf8 ;
USE `creditos` ;

-- -----------------------------------------------------
-- Table `creditos`.`MAESTROS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`MAESTROS` ;

CREATE TABLE IF NOT EXISTS `creditos`.`MAESTROS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `PARENT_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MAESTROS_MAESTROS_idx` (`PARENT_ID` ASC),
  CONSTRAINT `fk_MAESTROS_MAESTROS`
    FOREIGN KEY (`PARENT_ID`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`CLIENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`CLIENTES` ;

CREATE TABLE IF NOT EXISTS `creditos`.`CLIENTES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(45) NULL,
  `APELLIDOS` VARCHAR(45) NULL,
  `SEXO` VARCHAR(1) NULL,
  `DOCUMENTO` VARCHAR(12) NULL,
  `EXPEDIDO` VARCHAR(45) NULL,
  `LUGARNACIMIENTO` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `DIRRESIDENCIA` VARCHAR(45) NULL,
  `FENACIMIENTO` DATE NULL,
  `EMAIL` VARCHAR(45) NULL,
  `TELEFONO` VARCHAR(10) NULL,
  `CELULAR` VARCHAR(14) NULL,
  `FEEXPEDICION` DATE NULL,
  `ESTADOCIVIL` INT NULL,
  `NIVELEDUCATIVO` INT NULL,
  `TIPOVIVIENDA` INT NULL,
  `ZONAVIVIENDA` INT NULL,
  `PERSONASCARGO` INT NULL,
  `OCUPACION` INT NULL,
  `TIPDOC` VARCHAR(10) NULL,
  `IDACUDIENTE` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CLIENTES_MAESTROS1_idx` (`ESTADOCIVIL` ASC),
  INDEX `fk_CLIENTES_MAESTROS2_idx` (`NIVELEDUCATIVO` ASC),
  INDEX `fk_CLIENTES_MAESTROS4_idx` (`ZONAVIVIENDA` ASC),
  INDEX `fk_CLIENTES_MAESTROS3_idx` (`TIPOVIVIENDA` ASC),
  INDEX `fk_CLIENTES_MAESTROS5_idx` (`OCUPACION` ASC),
  INDEX `fk_CLIENTES_CLIENTES1_idx` (`IDACUDIENTE` ASC),
  CONSTRAINT `fk_CLIENTES_MAESTROS1`
    FOREIGN KEY (`ESTADOCIVIL`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_MAESTROS2`
    FOREIGN KEY (`NIVELEDUCATIVO`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_MAESTROS3`
    FOREIGN KEY (`TIPOVIVIENDA`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_MAESTROS4`
    FOREIGN KEY (`ZONAVIVIENDA`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_MAESTROS5`
    FOREIGN KEY (`OCUPACION`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_CLIENTES1`
    FOREIGN KEY (`IDACUDIENTE`)
    REFERENCES `creditos`.`CLIENTES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`VINCULACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`VINCULACION` ;

CREATE TABLE IF NOT EXISTS `creditos`.`VINCULACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENTIDADAHORRO` VARCHAR(45) NULL,
  `VLRAHORRO` INT NULL,
  `ENTIDADCESANTIAS` VARCHAR(45) NULL,
  `VLRCESANTIAS` INT NULL,
  `VLROTROS` INT NULL,
  `CAPACIDADDEUDA` INT NULL,
  `NOMBREEMPRESA` VARCHAR(45) NULL,
  `FEINGRESO` DATE NULL,
  `TIPOEMPRESA` INT NULL,
  `TIPOVIVIENDA` INT NULL,
  `CARGO` VARCHAR(45) NULL,
  `DIRECCIONTRABAJO` VARCHAR(100) NULL,
  `CIUDADTRABAJO` VARCHAR(45) NULL,
  `BARRIO` VARCHAR(45) NULL,
  `INGRESOS` INT NULL,
  `EGRESOS` INT NULL,
  `OTROSINGRESOS` INT NULL,
  `INGRESOSSALARIO` INT NULL,
  `ISDEUDAS` VARCHAR(1) NULL,
  `FECORTE` DATE NULL,
  `ISDECLARANTE` VARCHAR(1) NULL,
  `PAGOCOOPERATIVA` MEDIUMTEXT NULL,
  `CUOTA` INT NULL,
  `ORIGEN` VARCHAR(45) NULL,
  `REFERENCIA1` VARCHAR(45) NULL,
  `DIRREFERENCIA1` VARCHAR(100) NULL,
  `TELREFERENCIA1` VARCHAR(45) NULL,
  `REFERENCIAF` VARCHAR(45) NULL,
  `DIRREFERENCIAF` VARCHAR(45) NULL,
  `TELREFERENCIAF` VARCHAR(10) NULL,
  `PARENTESCOREFERENCIA` VARCHAR(45) NULL,
  `REFERENCIACOOP` VARCHAR(45) NULL,
  `REFERENCIACOOPAFI` INT NULL,
  `REFERENCIACOOPTEL` VARCHAR(12) NULL,
  `REFERENCIACOOPAFIM` INT NULL,
  `LUGARENTREVISTA` VARCHAR(45) NULL,
  `FEENTREVISTA` DATE NULL,
  `RESULTADOENTREVISTA` VARCHAR(10) NULL,
  `IDCLIENTE` INT NOT NULL,
  `ISCAJACOMPENSACION` VARCHAR(2) NULL,
  `ISSUBSIDIOMUNICIPAL` VARCHAR(2) NULL,
  `ISSUBSIDIODEPARTAMENTAL` VARCHAR(2) NULL,
  `VLRSUBSIDIOM` INT NULL,
  `VLRSUBSIDIOD` INT NULL,
  `MONTODEUDA` INT NULL,
  `ENTIDADDEUDA` VARCHAR(45) NULL,
  `PASIVOS` INT NULL,
  `ENTIDADCAJA` VARCHAR(45) NULL,
  `SUBSIDIOCAJA` INT NULL,
  `TIPOCONTRATO` INT NULL,
  `VIGENCIA` INT NULL,
  `REFERENCIAC` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_VINCULACION_CLIENTES1_idx` (`IDCLIENTE` ASC),
  INDEX `fk_VINCULACION_MAESTROS1_idx` (`TIPOEMPRESA` ASC),
  INDEX `fk_VINCULACION_MAESTROS3_idx` (`REFERENCIACOOPAFI` ASC),
  INDEX `fk_VINCULACION_MAESTROS2_idx` (`TIPOVIVIENDA` ASC),
  INDEX `fk_VINCULACION_MAESTROS4_idx` (`TIPOCONTRATO` ASC),
  CONSTRAINT `fk_VINCULACION_CLIENTES1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `creditos`.`CLIENTES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINCULACION_MAESTROS1`
    FOREIGN KEY (`TIPOEMPRESA`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINCULACION_MAESTROS2`
    FOREIGN KEY (`TIPOVIVIENDA`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINCULACION_MAESTROS3`
    FOREIGN KEY (`REFERENCIACOOPAFI`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINCULACION_MAESTROS4`
    FOREIGN KEY (`TIPOCONTRATO`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`BENEFICIARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`BENEFICIARIO` ;

CREATE TABLE IF NOT EXISTS `creditos`.`BENEFICIARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `FECHANACIMIENTO` DATE NULL,
  `PARENTESCO` VARCHAR(45) NULL,
  `TELEFONO` VARCHAR(45) NULL,
  `DESIGNACION` VARCHAR(45) NULL,
  `IDVINCULACION` INT NOT NULL,
  `DOCUMENTO` VARCHAR(15) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_BENEFICIARIO_VINCULACION1_idx` (`IDVINCULACION` ASC),
  CONSTRAINT `fk_BENEFICIARIO_VINCULACION1`
    FOREIGN KEY (`IDVINCULACION`)
    REFERENCES `creditos`.`VINCULACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`CONFIRMACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`CONFIRMACION` ;

CREATE TABLE IF NOT EXISTS `creditos`.`CONFIRMACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DIRECCION` TINYINT(1) NULL,
  `TELEFONO` TINYINT(1) NULL,
  `REFERENCIAP` TINYINT(1) NULL,
  `REFERENCIAF` TINYINT(1) NULL,
  `DATOSLABORALES` TINYINT(1) NULL,
  `INFORMACIONF` TINYINT(1) NULL,
  `CURSO` TINYINT(1) NULL,
  `OTRO` VARCHAR(45) NULL,
  `ESTADO` TINYINT(1) NULL,
  `IDVINCULACION` INT NOT NULL,
  `REFERENCIAC` TINYINT(1) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONFIRMACION_VINCULACION1_idx` (`IDVINCULACION` ASC),
  CONSTRAINT `fk_CONFIRMACION_VINCULACION1`
    FOREIGN KEY (`IDVINCULACION`)
    REFERENCES `creditos`.`VINCULACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`CREDITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`CREDITO` ;

CREATE TABLE IF NOT EXISTS `creditos`.`CREDITO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATETIME NULL,
  `VALOR` FLOAT NULL,
  `INTERES` FLOAT NULL,
  `PLAZO` INT NULL,
  `IDCLIENTE` INT NOT NULL,
  `IDMAESTRO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CREDITO_CLIENTES2_idx` (`IDCLIENTE` ASC),
  INDEX `fk_CREDITO_MAESTROS1_idx` (`IDMAESTRO` ASC),
  CONSTRAINT `fk_CREDITO_CLIENTES2`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `creditos`.`CLIENTES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITO_MAESTROS1`
    FOREIGN KEY (`IDMAESTRO`)
    REFERENCES `creditos`.`MAESTROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`DETALLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`DETALLE` ;

CREATE TABLE IF NOT EXISTS `creditos`.`DETALLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NULL,
  `SALDOINICIAL` FLOAT NULL,
  `INTERESES` FLOAT NULL,
  `CUOTA` FLOAT NULL,
  `AMORTIZACION` FLOAT NULL,
  `SALDOFINAL` FLOAT NULL,
  `PERIODO` INT NULL,
  `IDCREDITO` INT NOT NULL,
  `ESTADO` VARCHAR(45) NULL,
  `FECHAPAGO` TIMESTAMP NULL,
  `VALORPAGADO` FLOAT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DETALLE_CREDITO1_idx` (`IDCREDITO` ASC),
  CONSTRAINT `fk_DETALLE_CREDITO1`
    FOREIGN KEY (`IDCREDITO`)
    REFERENCES `creditos`.`CREDITO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`APORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`APORTE` ;

CREATE TABLE IF NOT EXISTS `creditos`.`APORTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` TIMESTAMP NULL,
  `VALOR` INT NULL,
  `IDCLIENTE` INT NULL,
  `TIPO` VARCHAR(2) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_APORTE_CLIENTES1_idx` (`IDCLIENTE` ASC),
  CONSTRAINT `fk_APORTE_CLIENTES1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `creditos`.`CLIENTES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditos`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `creditos`.`USUARIO` (
  `USER` VARCHAR(10) NOT NULL,
  `PASSWORD` VARCHAR(45) NULL,
  PRIMARY KEY (`USER`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
